spring:
  r2dbc:
    url: r2dbc:postgresql://0.0.0.0:5432/postgres?schema=anime
    username: root
    password: root
logging:
  level:
    org:
      springframework:
        data:
          r2dbc: DEBUG

